* myuron's emacs configuration

init.orgをorg-babelを用いてinit.elに変換し、~/.emacs.d/に配置する。

パッケージのインストールはnixで行い、設定のみinit.orgに定義する。(inti.orgでensure tは不要)

初期表示に関する設定は[[./early-init.org][early-init.org]]に定義する

** header

#+begin_src emacs-lisp :tangle yes
  ;;; package --- initial configuration -*- lexical-binding: t; -*-
  ;;; Commentary:
  ;;; Code:
#+end_src

** Emacs標準機能の設定

*** フォント

#+begin_src emacs-lisp :tangle yes
  (let ((mono-spaced-font "HackGen Console NF")
        (proportionately-spaced-font "Sans"))
    (set-face-attribute 'default nil :family mono-spaced-font :height 120)
    (set-face-attribute 'fixed-pitch nil :family mono-spaced-font :height 1.0)
    (set-face-attribute 'variable-pitch nil :family proportionately-spaced-font :height 1.0))    
#+end_src

*** yes-or-noをy-or-nに変更

#+begin_src emacs-lisp :tangle yes
  (setq use-short-answers t)
#+end_src

*** バックアップファイル、ロックファイルを作成しない

#+begin_src emacs-lisp :tangle yes
  (setq make-backup-files nil)
  (setq backup-inhibited nil)
  (setq create-lockfiles nil)
#+end_src

*** ビープ音を無効化

#+begin_src emacs-lisp :tangle yes
  (setq ring-bell-function 'ignore)
#+end_src

*** デーモン起動

#+begin_src emacs-lisp :tangle yes
  (use-package server
    :config
    (server-mode))
#+end_src

*** 最後のカーソル位置を保存する

#+begin_src emacs-lisp :tangle yes
  (use-package saveplace
    :init
    (save-place-mode))
#+end_src

*** ファイルの閲覧履歴を保存する

#+begin_src emacs-lisp :tangle yes
  (use-package recentf
    :config
    (setq recentf-max-saved-items 1024)
    (recentf-mode))
#+end_src

*** コマンドの履歴を保存

ミニバッファの入力履歴をファイルに保存し、セッション間で共有する。

#+begin_src emacs-lisp :tangle yes
  (use-package savehist
    :hook
    (after-init . savehist-mode))
#+end_src

*** 対応括弧を自動補完

#+begin_src emacs-lisp :tangle yes
  (use-package elec-pair
    :config
    (electric-pair-mode))
#+end_src

*** 他プロセスの編集をバッファに反映

#+begin_src emacs-lisp :tangle yes
  (use-package autorevert
    :init
    (global-auto-revert-mode 1))
#+end_src

*** native-compの警告を表示しない

#+begin_src emacs-lisp :tangle yes
  (setq native-comp-async-report-warnings-errors 'silent)
#+end_src

*** 末尾のスペースやタブを可視化

#+begin_src emacs-lisp :tangle yes
  (setq show-trailing-whitespace t)
#+end_src

*** 行番号表示

#+begin_src emacs-lisp :tangle yes
  (use-package display-line-numbers
    :custom (display-line-numbers-width 4)
    :init
    (global-display-line-numbers-mode 1))
#+end_src

*** 現在行の強調表示

#+begin_src emacs-lisp :tangle yes
  (use-package hl-line
    :init
    (global-hl-line-mode 1))
#+end_src

*** delsel

テキスト挿入時に選択したテキストを削除する

#+begin_src emacs-lisp :tangle yes
  (use-package delsel
    :hook
    (after-init . delete-selection-mode))
#+end_src

*** tab-bar-mode

バッファをタブで管理する機能を提供する。

#+begin_src emacs-lisp :tangle yes
  (use-package tab-bar
    :init
    (tab-bar-mode)
    (tab-bar-history-mode))
#+end_src

*** flymake

リアルタイムでコードのエラーや警告を検出し、表示するシンタックスチェックフレームワーク。

#+begin_src emacs-lisp :tangle yes
  (use-package flymake
    :hook ((prog-mode
  	  conf-mode) . flymake-mode)
    :init
    (setq flymake-indicator-type nil)
    (setq flymake-show-diagnostics-at-end-of-line t))
#+end_src

*** キーバインドガイド

#+begin_src emacs-lisp :tangle yes
  (use-package which-key
    :config
    (which-key-mode))
#+end_src

** packages

*** [[https://github.com/protesilaos/modus-themes][modus-themes]]

#+begin_src emacs-lisp :tangle yes
  (use-package modus-themes
    :config
    (load-theme 'modus-vivendi-tinted :no-confirm-loading))
#+end_src

*** moody

#+begin_src emacs-lisp :tangle yes
  (use-package moody
    :config
    (moody-replace-mode-line-front-space)
    (moody-replace-mode-line-buffer-identification)
    (moody-replace-vc-mode))
#+end_src

*** [[https://github.com/rainstormstudio/nerd-icons.el][nerd-icons]]

#+begin_src emacs-lisp :tangle yes
  (use-package nerd-icons)
#+end_src

*** [[https://github.com/rainstormstudio/nerd-icons-completion][nerd-icons-completion]]

marginaliaでnerd-iconsを有効化

#+begin_src emacs-lisp :tangle yes
  (use-package nerd-icons-completion
    :after marginalia
    :config
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))
#+end_src

*** [[https://github.com/LuigiPiucco/nerd-icons-corfu][nerd-icons-corfu]]

corfuでnerd-iconsを有効化

#+begin_src emacs-lisp :tangle yes
  (use-package nerd-icons-corfu
    :after corfu
    :config
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))
#+end_src

*** [[https://github.com/rainstormstudio/nerd-icons-dired][nerd-icons-dired]]

diredでnerd-iconsを有効化

#+begin_src emacs-lisp :tangle yes
  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))
#+end_src


*** dired

[標準]diredは、ディレクトリの内容をバッファ上に一覧表示し、ファイルのコピー、移動、削除、リネームなどをキー操作で行なうファイルマネージャー。

#+begin_src emacs-lisp :tangle yes
  (use-package dired
    :commands (dired)
    :hook
    ((dired-mode . dired-hide-details-mode)
     (dired-mode . hl-line-mode))
    :config
    (setq dired-recursive-copies 'always)
    (setq dired-recursive-deletes 'alwasy)
    (setq delete-by-moving-to-trash t)
    (setq dired-dwim-target t))
#+end_src

*** [[https://github.com/fuco1/dired-hacks#dired-subtree][dired-subtree]]

dired-subtreeは、dired上でサブディレクトリを別バッファに移動せずにその場でツリー状に展開、折りたたみを実現する。

#+begin_src emacs-lisp :tangle yes
  (use-package dired-subtree
    :after dired
    :bind
    (:map dired-mode-map
  	("<tab>" . dired-subtree-toggle)
  	("TAB" . dired-subtree-toggle)
  	("<backtab>" . dired-subtree-remove)
  	("S-TAB" . dired-subtree-remove))
    :config
    (setq dired-subtree-use-backgrounds nil))
#+end_src

*** consult

#+begin_src emacs-lisp :tangle yes
  (use-package consult
    :bind
    (("C-c f" . consult-fd)
     ("C-c g" . consult-ripgrep))
    :config
    (setq consult-preview-key "M-."))
#+end_src

*** [[https://github.com/emacs-evil/evil][evil]]

evilは、Vimのモーダル編集を再現する。

#+begin_src emacs-lisp :tangle yes
  (use-package evil
    :init
    (evil-mode 1))
#+end_src

*** [[https://github.com/takeokunn/nskk.el][nskk]]

nskkは、SKK(Simple Kana to Kanji)方式の日本語入力を実現する。

#+begin_src emacs-lisp :tanble yes
  (use-package nskk
    :custom
    (nskk-dics-system-dictionary-files
     '("~/.nix-profile/share/skk/SKK-JISYO.L"))
    :config
    (nskk-global-mode 1))
#+end_src

*** [[https://github.com/magit/magit][magit]]

magitは、Git Client機能を提供する。

#+begin_src emacs-lisp :tangle yes
  (use-package magit
    :bind
    ("C-c g" . magit-status))
#+end_src

*** eat

eatは、Emacs上で動作するターミナルエミュレータ機能を提供する。

#+begin_src emacs-lisp :tangle yes
  (use-package eat
    :bind
    ("C-c t" . eat))
#+end_src

*** elfeed

elfeedは、Emacs上で動作するRSSリーダー機能を提供する。

#+begin_src emacs-lisp :tangle yes
  (use-package elfeed
    :config
    (setq elfeed-feeds
  	'("https://claude-media.com/rss.xml")))
#+end_src

** Completion

*** [[https://github.com/minad/vertico][vertico]]

verticoは、補完候補を垂直表示する。

#+begin_src emacs-lisp :tangle yes
  (use-package vertico
    :hook
    (after-init . vertico-mode))
#+end_src

*** [[https://github.com/tumashu/vertico-posframe][vertico-posframe]]

vertico-posframeは、補完候補を中央に表示する。

#+begin_src emacs-lisp :tangle yes
  (use-package vertico-posframe
    :hook
    (after-init . vertico-posframe-mode))
#+end_src

*** [[https://github.com/oantolin/orderless][orderless]]

orderlessは、候補を順序不同で絞りこむ。

#+begin_src emacs-lisp :tangle yes
  (use-package orderless
    :config
    (setq completion-styles '(orderless basic))
    (setq completion-category-defaults nil)
    (setq completion-category-overrides nil))
#+end_src

*** [[https://github.com/minad/marginalia][marginalia]]

marginaliaは、補完候補に付随情報を追加する。

#+begin_src emacs-lisp :tangle yes
  (use-package marginalia
    :hook
    (after-init . marginalia-mode))
#+end_src

*** [[https://github.com/minad/corfu][corfu]]

corfuは、カーソル位置に補完候補をポップアップ表示する軽量な入力補完UI。

#+begin_src emacs-lisp :tangle yes
  (use-package corfu
    :init
    (setq corfu-auto t)
    (setq corfu-quit-no-match 'separator)
    (global-corfu-mode)
    :config
    ;; nskkはself-insert-commandをnskk-self-insert等にremapするため、
    ;; corfu-autoの発火対象コマンドに追加する
    ;; (corfu-auto.elはcorfu-mode有効化時に遅延ロードされる)
    (with-eval-after-load 'corfu-auto
      (dolist (cmd '("\\`nskk-self-insert\\'" "\\`nskk-handle-"))
        (add-to-list 'corfu-auto-commands cmd))))
#+end_src

*** cape

#+begin_src emacs-lisp :tangle yes
  (use-package cape
    :bind
    ("C-c p" . cape-prefix-map)
    :init
    (advice-add 'eglot-completion-at-point :around #'cape-wrap-buster)
    (advice-add 'eglot-completion-at-point :around #'cape-wrap-nonexclusive)
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-keyword)
    (add-hook 'completion-at-point-functions #'cape-elisp-block))
#+end_src

** LSP

*** lsp-mode
#+begin_src emacs-lisp :tangle yes
  (use-package eglot
    :config
    (add-to-list 'eglot-server-programs '(nix-ts-mode . "nixd"))
    (add-to-list 'eglot-server-programs '(go-mode . "gopls"))
    (add-to-list 'eglot-server-programs '(rust-mode . "rust-analyzer"))
    :hook
    (nix-ts-mode . eglot-ensure)
    (go-mode . eglot-ensure)
    (rust-mode . eglot-ensure))
#+end_src

*** nix-ts-mode

#+begin_src emacs-lisp :tangle yes
  (use-package nix-ts-mode
    :mode "\\.nix\\'")
#+end_src

*** go-mode

#+begin_src emacs-lisp :tangle yes
  (use-package go-mode
    :mode "\\.go\\'")
#+end_src

*** rust-mode

#+begin_src emacs-lisp :tangle yes
  (use-package rust-mode
    :mode "\\.rs\\'")
#+end_src

** Org-mode

#+begin_src emacs-lisp :tangle yes
  (use-package org
    :bind
    ("C-c o a" . org-agenda)
    ("C-c o c" . org-capture)
    :config
    (setq org-todo-keywords
  	'(sequence "TODO(t)" "DOIN(i)" "WAIT(w)"
  		   "|" "DONE(d)" "SKIP(s)"))
    (setq org-todo-keyword-faces
  	'(
  	  ("WAIT" . (:foreground "CadetBlue3" :weight bold))
  	  ("TODO" . (:foreground "LightGoldenrod3" :weight bold))))
    (setq org-log-done nil)
    (setq org-fontify-done-headline nil)
    (setq org-directory "~/org/")
    (setq org-agenda-files (list org-directory))
    (setq org-agenda-window-setup 'current-window)
    (setq hl-line-face 'underline)
    (setq calendar-holidays nil)
    (setq org-capture-templetes
  	'(
  	  ("t" "TODO" entry (file+headline "~/org/0_inbox.org" "[#C] REMIND")
  	   "* REMD [#C] %? (wrote on %U)")
  	  )))
#+end_src

** Tips

- C-c C-e: (org-export-dispatch)orgファイルを様々なファイル形式でエクスポート
- C-c C-,: orgファイルでスニペットを挿入する
- C-c '  : (org-edit-special)orgファイルのコードブロックで言語仕様にあった別バッファを表示して編集できる
