[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
fetch.github = "vim-skk/skkeleton"

[cmp-skkeleton]
src.git = "https://github.com/uga-rosa/cmp-skkeleton"
fetch.github = "uga-rosa/cmp-skkeleton"

[nskk]
src.git = "https://github.com/takeokunn/nskk.el"
fetch.github = "takeokunn/nskk.el"

[om-dash]
src.git = "https://github.com/gavv/om-dash"
fetch.github = "gavv/om-dash"