# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cmp-skkeleton = {
    pname = "cmp-skkeleton";
    version = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "cmp-skkeleton";
      rev = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
      fetchSubmodules = false;
      sha256 = "sha256-Odg0cmLML2L4YVcrMt7Lrie1BAl7aNEq6xqJN3/JhZs=";
    };
    date = "2023-11-26";
  };
  nskk = {
    pname = "nskk";
    version = "8757fa3f38ad0cee20606d0fb5d369ecb845503d";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "nskk.el";
      rev = "8757fa3f38ad0cee20606d0fb5d369ecb845503d";
      fetchSubmodules = false;
      sha256 = "sha256-LUNe0TQPeFJ1+TTPP3OByO+7WCnaK/sBT8BWvZ1Ycvk=";
    };
    date = "2026-07-04";
  };
  om-dash = {
    pname = "om-dash";
    version = "e89132365aef923c0493566f4ace5ece02c759ad";
    src = fetchFromGitHub {
      owner = "gavv";
      repo = "om-dash";
      rev = "e89132365aef923c0493566f4ace5ece02c759ad";
      fetchSubmodules = false;
      sha256 = "sha256-vkKm8F+/8B+Fo0hNyd+f8Zz79wfcJPcJMIuxNoo15gs=";
    };
    date = "2025-03-11";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "770b265dd115dba96ea5314642e35764654ef08f";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "770b265dd115dba96ea5314642e35764654ef08f";
      fetchSubmodules = false;
      sha256 = "sha256-Gsl/LqUY8szRqYLnDVyDOIDCw+cisoKsS5Fl1zQ+unM=";
    };
    date = "2026-05-05";
  };
}
