# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cmp-skkeleton = {
    pname = "cmp-skkeleton";
    version = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "cmp-skkeleton";
      rev = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
      fetchSubmodules = false;
      sha256 = "sha256-Odg0cmLML2L4YVcrMt7Lrie1BAl7aNEq6xqJN3/JhZs=";
    };
    date = "2023-11-26";
  };
  nskk = {
    pname = "nskk";
    version = "e429c83b4c75042444c6d30d3fee79be6877febe";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "nskk.el";
      rev = "e429c83b4c75042444c6d30d3fee79be6877febe";
      fetchSubmodules = false;
      sha256 = "sha256-sc64yUTmAjT6t4pSzYv5bDTPDi8nyzrzr83Qtgk1jl4=";
    };
    date = "2026-05-16";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "770b265dd115dba96ea5314642e35764654ef08f";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "770b265dd115dba96ea5314642e35764654ef08f";
      fetchSubmodules = false;
      sha256 = "sha256-Gsl/LqUY8szRqYLnDVyDOIDCw+cisoKsS5Fl1zQ+unM=";
    };
    date = "2026-05-05";
  };
}
